# DeepLearningBasics

In [18]:
# DeepLearningBasics

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [19]:
import warnings
warnings.filterwarnings('ignore')

In [20]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [21]:
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [22]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [23]:
X = df.drop('needs_water', axis=1)
y = df['needs_water']

In [24]:
# Applying min max scaler

X_min = X.min()
X_max = X.max()

X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [25]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [26]:
X_train, X_test,y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42, stratify=y)

In [27]:
X_train.shape

(12, 3)

In [28]:
# to get the number columns in training data

X_train.shape[1]

3

In [29]:
#ANN

model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)), # 3 input layers
    layers.Dense(8, activation='relu'), # 8 hidden layers and activation functoion relu
    layers.Dense(1, activation='sigmoid') # 1 output layer and activation sigmoid function
])

In [30]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [31]:
history = model.fit(
    X_train.values, y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step - accuracy: 0.6042 - loss: 0.6653 - val_accuracy: 0.5000 - val_loss: 0.6872
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5729 - loss: 0.6687 - val_accuracy: 0.5000 - val_loss: 0.6871
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5729 - loss: 0.6711 - val_accuracy: 0.5000 - val_loss: 0.6870
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5417 - loss: 0.6594 - val_accuracy: 0.5000 - val_loss: 0.6868
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6354 - loss: 0.6430 - val_accuracy: 0.5000 - val_loss: 0.6865
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4479 - loss: 0.6820 - val_accuracy: 0.5000 - val_loss: 0.6863
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6354 - loss: 0.6454 - val_accuracy: 0.5000 - val_loss: 0.6860
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5417 - loss: 0.6574 - val_accuracy: 0.5000 - val_loss: 0.6858
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4792 - loss: 0.6811 - val_accuracy: 0.5000 - val_loss: 0.6855
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5417 - loss: 0.6746 - val_accuracy: 0.5000 - val_loss: 0.6853
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6354 - loss: 0.6463 - val_accuracy: 0.5000 - val_loss: 0.6850
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4167 - loss: 0.6946 - val_accuracy: 0.5000 - val_loss: 0.6848
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6354 - loss: 0.6482 - val_accuracy: 0.5000 - val_loss: 0.6845
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5729 - loss: 0.6371 - val_accuracy: 0.5000 - val_loss: 0.6842
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5104 - loss: 0.6776 - val_accuracy: 0.5000 - val_loss: 0.6840
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4792 - loss: 0.6740 - val_accuracy: 0.5000 - val_loss: 0.6837
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7292 - loss: 0.6152 - val_accuracy: 0.5000 - val_loss: 0.6834
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6354 - loss: 0.6350 - val_accuracy: 0.5000 - val_loss: 0.6831
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5729 - loss: 0.6403 - val_accuracy: 0.5000 - val_loss: 0.6828
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5417 - loss: 0.6721 - val_accuracy: 0.5000 - val_loss: 0.6825
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6042 - loss: 0.6600 - val_accuracy: 0.5000 - val_loss: 0.6822
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6354 - loss: 0.6306 - val_accuracy: 0.5000 - val_loss: 0.6819
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6330 - val_accuracy: 0.5000 - val_loss: 0.6815
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5104 - loss: 0.6625 - val_accuracy: 0.5000 - val_loss: 0.6812
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5104 - loss: 0.6461 - val_accuracy: 0.5000 - val_loss: 0.6809
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6458 - loss: 0.6366 - val_accuracy: 0.5000 - val_loss: 0.6806
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6354 - loss: 0.6340 - val_accuracy: 0.5000 - val_loss: 0.6803
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7708 - loss: 0.6467 - val_accuracy: 0.5000 - val_loss: 0.6800
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6771 - loss: 0.6300 - val_accuracy: 0.5000 - val_loss: 0.6797
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7083 - loss: 0.6516 - val_accuracy: 0.5000 - val_loss: 0.6794
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6771 - loss: 0.6434 - val_accuracy: 0.5000 - val_loss: 0.6790
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7083 - loss: 0.6299 - val_accuracy: 0.5000 - val_loss: 0.6787
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5521 - loss: 0.6810 - val_accuracy: 0.5000 - val_loss: 0.6784
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8021 - loss: 0.6228 - val_accuracy: 0.5000 - val_loss: 0.6781
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6481 - val_accuracy: 0.5000 - val_loss: 0.6778
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6458 - loss: 0.6582 - val_accuracy: 0.5000 - val_loss: 0.6775
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7083 - loss: 0.6313 - val_accuracy: 0.5000 - val_loss: 0.6771
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5521 - loss: 0.6651 - val_accuracy: 0.5000 - val_loss: 0.6768
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6771 - loss: 0.6438 - val_accuracy: 0.5000 - val_loss: 0.6765
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6771 - loss: 0.6551 - val_accuracy: 0.5000 - val_loss: 0.6762
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8021 - loss: 0.6216 - val_accuracy: 0.5000 - val_loss: 0.6758
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6771 - loss: 0.6496 - val_accuracy: 0.5000 - val_loss: 0.6755
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5208 - loss: 0.6723 - val_accuracy: 0.5000 - val_loss: 0.6752
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5521 - loss: 0.6710 - val_accuracy: 0.5000 - val_loss: 0.6749
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7396 - loss: 0.6207 - val_accuracy: 0.5000 - val_loss: 0.6745
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.6629 - val_accuracy: 0.5000 - val_loss: 0.6742
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6458 - loss: 0.6465 - val_accuracy: 0.5000 - val_loss: 0.6739
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7083 - loss: 0.6228 - val_accuracy: 0.5000 - val_loss: 0.6736
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6771 - loss: 0.6303 - val_accuracy: 0.5000 - val_loss: 0.6732
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7396 - loss: 0.6348 - val_accuracy: 0.5000 - val_loss: 0.6729
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6771 - loss: 0.6386 - val_accuracy: 0.5000 - val_loss: 0.6726
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7083 - loss: 0.6388 - val_accuracy: 0.5000 - val_loss: 0.6722
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6771 - loss: 0.6416 - val_accuracy: 0.5000 - val_loss: 0.6719
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6146 - loss: 0.6289 - val_accuracy: 0.5000 - val_loss: 0.6716
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6771 - loss: 0.6300 - val_accuracy: 0.5000 - val_loss: 0.6712
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6458 - loss: 0.6553 - val_accuracy: 0.5000 - val_loss: 0.6709
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7396 - loss: 0.6093 - val_accuracy: 0.5000 - val_loss: 0.6705
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7083 - loss: 0.6417 - val_accuracy: 0.5000 - val_loss: 0.6702
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7708 - loss: 0.6091 - val_accuracy: 0.5000 - val_loss: 0.6698
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6458 - loss: 0.6517 - val_accuracy: 0.5000 - val_loss: 0.6694
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6771 - loss: 0.6429 - val_accuracy: 0.5000 - val_loss: 0.6690
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7083 - loss: 0.6178 - val_accuracy: 0.5000 - val_loss: 0.6686
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6458 - loss: 0.6577 - val_accuracy: 0.5000 - val_loss: 0.6683
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6771 - loss: 0.6276 - val_accuracy: 0.5000 - val_loss: 0.6679
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6146 - loss: 0.6499 - val_accuracy: 0.5000 - val_loss: 0.6675
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6771 - loss: 0.6390 - val_accuracy: 0.5000 - val_loss: 0.6671
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6771 - loss: 0.6420 - val_accuracy: 0.5000 - val_loss: 0.6667
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6146 - loss: 0.6371 - val_accuracy: 0.5000 - val_loss: 0.6663
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8021 - loss: 0.6023 - val_accuracy: 0.5000 - val_loss: 0.6659
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7188 - loss: 0.6278 - val_accuracy: 0.5000 - val_loss: 0.6656
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7396 - loss: 0.6317 - val_accuracy: 0.5000 - val_loss: 0.6652
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8021 - loss: 0.5994 - val_accuracy: 0.5000 - val_loss: 0.6648
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6562 - loss: 0.6382 - val_accuracy: 0.5000 - val_loss: 0.6645
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7083 - loss: 0.6106 - val_accuracy: 0.5000 - val_loss: 0.6641
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7708 - loss: 0.6047 - val_accuracy: 0.5000 - val_loss: 0.6637
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7083 - loss: 0.6221 - val_accuracy: 0.5000 - val_loss: 0.6633
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7188 - loss: 0.6320 - val_accuracy: 0.5000 - val_loss: 0.6629
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.6241 - val_accuracy: 0.5000 - val_loss: 0.6625
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8021 - loss: 0.5942 - val_accuracy: 0.5000 - val_loss: 0.6621
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.6352 - val_accuracy: 0.5000 - val_loss: 0.6617
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5938 - loss: 0.6567 - val_accuracy: 0.5000 - val_loss: 0.6613
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8438 - loss: 0.5961 - val_accuracy: 0.5000 - val_loss: 0.6609
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7188 - loss: 0.6358 - val_accuracy: 0.5000 - val_loss: 0.6605
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6562 - loss: 0.6472 - val_accuracy: 0.5000 - val_loss: 0.6601
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7188 - loss: 0.6113 - val_accuracy: 0.5000 - val_loss: 0.6597
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7812 - loss: 0.6242 - val_accuracy: 0.5000 - val_loss: 0.6593
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7500 - loss: 0.6252 - val_accuracy: 0.5000 - val_loss: 0.6589
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8438 - loss: 0.5938 - val_accuracy: 0.5000 - val_loss: 0.6585
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.6126 - val_accuracy: 0.5000 - val_loss: 0.6581
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7188 - loss: 0.6405 - val_accuracy: 0.5000 - val_loss: 0.6578
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8438 - loss: 0.6194 - val_accuracy: 0.7500 - val_loss: 0.6573
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6562 - loss: 0.6345 - val_accuracy: 0.7500 - val_loss: 0.6570
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6562 - loss: 0.6262 - val_accuracy: 0.7500 - val_loss: 0.6566
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6562 - loss: 0.6282 - val_accuracy: 0.7500 - val_loss: 0.6562
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7812 - loss: 0.6325 - val_accuracy: 0.7500 - val_loss: 0.6558
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6875 - loss: 0.6275 - val_accuracy: 0.7500 - val_loss: 0.6553
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8750 - loss: 0.5851 - val_accuracy: 0.7500 - val_loss: 0.6549
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6555 - val_accuracy: 0.7500 - val_loss: 0.6545
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6875 - loss: 0.6374 - val_accuracy: 0.7500 - val_loss: 0.6541
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8438 - loss: 0.6159 - val_accuracy: 0.7500 - val_loss: 0.6537